// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSply_ZuktKPHXZ7-jYp3V3a7RtQlJUek',
    appId: '1:642296570221:web:ae9c62dec907f29a8e3a64',
    messagingSenderId: '642296570221',
    projectId: 'sales-application-25165',
    authDomain: 'sales-application-25165.firebaseapp.com',
    storageBucket: 'sales-application-25165.firebasestorage.app',
    measurementId: 'G-0Z5F5VZ1DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgQmcYj1XmtAwjeGh5a6FjkbSX3sq-7M',
    appId: '1:642296570221:android:c23eede9310df2d88e3a64',
    messagingSenderId: '642296570221',
    projectId: 'sales-application-25165',
    storageBucket: 'sales-application-25165.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ZciyNT9Azi4w6YXlzUwqJfhsyocAT-I',
    appId: '1:642296570221:ios:fa2a332e56ddbba38e3a64',
    messagingSenderId: '642296570221',
    projectId: 'sales-application-25165',
    storageBucket: 'sales-application-25165.firebasestorage.app',
    iosBundleId: 'com.example.banHang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ZciyNT9Azi4w6YXlzUwqJfhsyocAT-I',
    appId: '1:642296570221:ios:fa2a332e56ddbba38e3a64',
    messagingSenderId: '642296570221',
    projectId: 'sales-application-25165',
    storageBucket: 'sales-application-25165.firebasestorage.app',
    iosBundleId: 'com.example.banHang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSply_ZuktKPHXZ7-jYp3V3a7RtQlJUek',
    appId: '1:642296570221:web:5abedf59478ebf528e3a64',
    messagingSenderId: '642296570221',
    projectId: 'sales-application-25165',
    authDomain: 'sales-application-25165.firebaseapp.com',
    storageBucket: 'sales-application-25165.firebasestorage.app',
    measurementId: 'G-JYJMFS1NTC',
  );

}